# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        oauthprovider:
            id: app.security.user_provider

        api_key_user_provider:
            id: app.security.api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/(?!api)
            anonymous: ~
            oauth:
                resource_owners:
                    google:             "/login/check-google"
                login_path:        /login
                use_forward:       false
                failure_path:      /login

                oauth_user_provider:
                    service: app.security.user_provider
            logout:
                path:   /logout
                target: /
            context: context_key

        # this should in theory not be needed
        ss:
            pattern: ^/api/key
            anonymous: ~

        secured_area_api_key:
            pattern: ^/api
            anonymous: ~
            context: context_key
            # firewall can NOT be stateless, because then context does not work
#            stateless: true
            simple_preauth:
                authenticator: app.security.api_key_authenticator
            provider: api_key_user_provider

    access_control:
        - { path: ^/api/key, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/stack, roles: ROLE_USER }
